/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardWalletManagementIndexRouteImport } from './routes/_dashboard/dashboard/wallet-management/index'
import { Route as DashboardDashboardTransactionsIndexRouteImport } from './routes/_dashboard/dashboard/transactions/index'
import { Route as DashboardDashboardReportsIndexRouteImport } from './routes/_dashboard/dashboard/reports/index'
import { Route as DashboardDashboardPartnersIndexRouteImport } from './routes/_dashboard/dashboard/partners/index'
import { Route as DashboardDashboardOperationsIndexRouteImport } from './routes/_dashboard/dashboard/operations/index'
import { Route as DashboardDashboardCorridorsIndexRouteImport } from './routes/_dashboard/dashboard/corridors/index'
import { Route as DashboardDashboardComplianceIndexRouteImport } from './routes/_dashboard/dashboard/compliance/index'
import { Route as AuthAuthVerifyEmailIndexRouteImport } from './routes/_auth/auth/verify-email/index'
import { Route as AuthAuthSignupIndexRouteImport } from './routes/_auth/auth/signup/index'
import { Route as AuthAuthRecoveryCodesIndexRouteImport } from './routes/_auth/auth/recovery-codes/index'
import { Route as AuthAuthMfaVerifyIndexRouteImport } from './routes/_auth/auth/mfa-verify/index'
import { Route as AuthAuthMfaSetupIndexRouteImport } from './routes/_auth/auth/mfa-setup/index'
import { Route as AuthAuthLoginIndexRouteImport } from './routes/_auth/auth/login/index'
import { Route as AuthAuthForgotPasswordIndexRouteImport } from './routes/_auth/auth/forgot-password/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardWalletManagementIndexRoute =
  DashboardDashboardWalletManagementIndexRouteImport.update({
    id: '/dashboard/wallet-management/',
    path: '/dashboard/wallet-management/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardTransactionsIndexRoute =
  DashboardDashboardTransactionsIndexRouteImport.update({
    id: '/dashboard/transactions/',
    path: '/dashboard/transactions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardReportsIndexRoute =
  DashboardDashboardReportsIndexRouteImport.update({
    id: '/dashboard/reports/',
    path: '/dashboard/reports/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardPartnersIndexRoute =
  DashboardDashboardPartnersIndexRouteImport.update({
    id: '/dashboard/partners/',
    path: '/dashboard/partners/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardOperationsIndexRoute =
  DashboardDashboardOperationsIndexRouteImport.update({
    id: '/dashboard/operations/',
    path: '/dashboard/operations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardCorridorsIndexRoute =
  DashboardDashboardCorridorsIndexRouteImport.update({
    id: '/dashboard/corridors/',
    path: '/dashboard/corridors/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardComplianceIndexRoute =
  DashboardDashboardComplianceIndexRouteImport.update({
    id: '/dashboard/compliance/',
    path: '/dashboard/compliance/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AuthAuthVerifyEmailIndexRoute =
  AuthAuthVerifyEmailIndexRouteImport.update({
    id: '/auth/verify-email/',
    path: '/auth/verify-email/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAuthSignupIndexRoute = AuthAuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthRecoveryCodesIndexRoute =
  AuthAuthRecoveryCodesIndexRouteImport.update({
    id: '/auth/recovery-codes/',
    path: '/auth/recovery-codes/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAuthMfaVerifyIndexRoute = AuthAuthMfaVerifyIndexRouteImport.update({
  id: '/auth/mfa-verify/',
  path: '/auth/mfa-verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthMfaSetupIndexRoute = AuthAuthMfaSetupIndexRouteImport.update({
  id: '/auth/mfa-setup/',
  path: '/auth/mfa-setup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthLoginIndexRoute = AuthAuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthForgotPasswordIndexRoute =
  AuthAuthForgotPasswordIndexRouteImport.update({
    id: '/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof RouteRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthAuthLoginIndexRoute
  '/auth/mfa-setup': typeof AuthAuthMfaSetupIndexRoute
  '/auth/mfa-verify': typeof AuthAuthMfaVerifyIndexRoute
  '/auth/recovery-codes': typeof AuthAuthRecoveryCodesIndexRoute
  '/auth/signup': typeof AuthAuthSignupIndexRoute
  '/auth/verify-email': typeof AuthAuthVerifyEmailIndexRoute
  '/dashboard/compliance': typeof DashboardDashboardComplianceIndexRoute
  '/dashboard/corridors': typeof DashboardDashboardCorridorsIndexRoute
  '/dashboard/operations': typeof DashboardDashboardOperationsIndexRoute
  '/dashboard/partners': typeof DashboardDashboardPartnersIndexRoute
  '/dashboard/reports': typeof DashboardDashboardReportsIndexRoute
  '/dashboard/transactions': typeof DashboardDashboardTransactionsIndexRoute
  '/dashboard/wallet-management': typeof DashboardDashboardWalletManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof RouteRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthAuthLoginIndexRoute
  '/auth/mfa-setup': typeof AuthAuthMfaSetupIndexRoute
  '/auth/mfa-verify': typeof AuthAuthMfaVerifyIndexRoute
  '/auth/recovery-codes': typeof AuthAuthRecoveryCodesIndexRoute
  '/auth/signup': typeof AuthAuthSignupIndexRoute
  '/auth/verify-email': typeof AuthAuthVerifyEmailIndexRoute
  '/dashboard/compliance': typeof DashboardDashboardComplianceIndexRoute
  '/dashboard/corridors': typeof DashboardDashboardCorridorsIndexRoute
  '/dashboard/operations': typeof DashboardDashboardOperationsIndexRoute
  '/dashboard/partners': typeof DashboardDashboardPartnersIndexRoute
  '/dashboard/reports': typeof DashboardDashboardReportsIndexRoute
  '/dashboard/transactions': typeof DashboardDashboardTransactionsIndexRoute
  '/dashboard/wallet-management': typeof DashboardDashboardWalletManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_auth/auth/forgot-password/': typeof AuthAuthForgotPasswordIndexRoute
  '/_auth/auth/login/': typeof AuthAuthLoginIndexRoute
  '/_auth/auth/mfa-setup/': typeof AuthAuthMfaSetupIndexRoute
  '/_auth/auth/mfa-verify/': typeof AuthAuthMfaVerifyIndexRoute
  '/_auth/auth/recovery-codes/': typeof AuthAuthRecoveryCodesIndexRoute
  '/_auth/auth/signup/': typeof AuthAuthSignupIndexRoute
  '/_auth/auth/verify-email/': typeof AuthAuthVerifyEmailIndexRoute
  '/_dashboard/dashboard/compliance/': typeof DashboardDashboardComplianceIndexRoute
  '/_dashboard/dashboard/corridors/': typeof DashboardDashboardCorridorsIndexRoute
  '/_dashboard/dashboard/operations/': typeof DashboardDashboardOperationsIndexRoute
  '/_dashboard/dashboard/partners/': typeof DashboardDashboardPartnersIndexRoute
  '/_dashboard/dashboard/reports/': typeof DashboardDashboardReportsIndexRoute
  '/_dashboard/dashboard/transactions/': typeof DashboardDashboardTransactionsIndexRoute
  '/_dashboard/dashboard/wallet-management/': typeof DashboardDashboardWalletManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa-setup'
    | '/auth/mfa-verify'
    | '/auth/recovery-codes'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/dashboard/compliance'
    | '/dashboard/corridors'
    | '/dashboard/operations'
    | '/dashboard/partners'
    | '/dashboard/reports'
    | '/dashboard/transactions'
    | '/dashboard/wallet-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa-setup'
    | '/auth/mfa-verify'
    | '/auth/recovery-codes'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/dashboard/compliance'
    | '/dashboard/corridors'
    | '/dashboard/operations'
    | '/dashboard/partners'
    | '/dashboard/reports'
    | '/dashboard/transactions'
    | '/dashboard/wallet-management'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_dashboard/dashboard/'
    | '/_auth/auth/forgot-password/'
    | '/_auth/auth/login/'
    | '/_auth/auth/mfa-setup/'
    | '/_auth/auth/mfa-verify/'
    | '/_auth/auth/recovery-codes/'
    | '/_auth/auth/signup/'
    | '/_auth/auth/verify-email/'
    | '/_dashboard/dashboard/compliance/'
    | '/_dashboard/dashboard/corridors/'
    | '/_dashboard/dashboard/operations/'
    | '/_dashboard/dashboard/partners/'
    | '/_dashboard/dashboard/reports/'
    | '/_dashboard/dashboard/transactions/'
    | '/_dashboard/dashboard/wallet-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/wallet-management/': {
      id: '/_dashboard/dashboard/wallet-management/'
      path: '/dashboard/wallet-management'
      fullPath: '/dashboard/wallet-management'
      preLoaderRoute: typeof DashboardDashboardWalletManagementIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/transactions/': {
      id: '/_dashboard/dashboard/transactions/'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardDashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/reports/': {
      id: '/_dashboard/dashboard/reports/'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardDashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/partners/': {
      id: '/_dashboard/dashboard/partners/'
      path: '/dashboard/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardDashboardPartnersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/operations/': {
      id: '/_dashboard/dashboard/operations/'
      path: '/dashboard/operations'
      fullPath: '/dashboard/operations'
      preLoaderRoute: typeof DashboardDashboardOperationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/corridors/': {
      id: '/_dashboard/dashboard/corridors/'
      path: '/dashboard/corridors'
      fullPath: '/dashboard/corridors'
      preLoaderRoute: typeof DashboardDashboardCorridorsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/compliance/': {
      id: '/_dashboard/dashboard/compliance/'
      path: '/dashboard/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardDashboardComplianceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/auth/verify-email/': {
      id: '/_auth/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthAuthVerifyEmailIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/signup/': {
      id: '/_auth/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/recovery-codes/': {
      id: '/_auth/auth/recovery-codes/'
      path: '/auth/recovery-codes'
      fullPath: '/auth/recovery-codes'
      preLoaderRoute: typeof AuthAuthRecoveryCodesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/mfa-verify/': {
      id: '/_auth/auth/mfa-verify/'
      path: '/auth/mfa-verify'
      fullPath: '/auth/mfa-verify'
      preLoaderRoute: typeof AuthAuthMfaVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/mfa-setup/': {
      id: '/_auth/auth/mfa-setup/'
      path: '/auth/mfa-setup'
      fullPath: '/auth/mfa-setup'
      preLoaderRoute: typeof AuthAuthMfaSetupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/login/': {
      id: '/_auth/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/forgot-password/': {
      id: '/_auth/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthForgotPasswordIndexRoute: typeof AuthAuthForgotPasswordIndexRoute
  AuthAuthLoginIndexRoute: typeof AuthAuthLoginIndexRoute
  AuthAuthMfaSetupIndexRoute: typeof AuthAuthMfaSetupIndexRoute
  AuthAuthMfaVerifyIndexRoute: typeof AuthAuthMfaVerifyIndexRoute
  AuthAuthRecoveryCodesIndexRoute: typeof AuthAuthRecoveryCodesIndexRoute
  AuthAuthSignupIndexRoute: typeof AuthAuthSignupIndexRoute
  AuthAuthVerifyEmailIndexRoute: typeof AuthAuthVerifyEmailIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthForgotPasswordIndexRoute: AuthAuthForgotPasswordIndexRoute,
  AuthAuthLoginIndexRoute: AuthAuthLoginIndexRoute,
  AuthAuthMfaSetupIndexRoute: AuthAuthMfaSetupIndexRoute,
  AuthAuthMfaVerifyIndexRoute: AuthAuthMfaVerifyIndexRoute,
  AuthAuthRecoveryCodesIndexRoute: AuthAuthRecoveryCodesIndexRoute,
  AuthAuthSignupIndexRoute: AuthAuthSignupIndexRoute,
  AuthAuthVerifyEmailIndexRoute: AuthAuthVerifyEmailIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardComplianceIndexRoute: typeof DashboardDashboardComplianceIndexRoute
  DashboardDashboardCorridorsIndexRoute: typeof DashboardDashboardCorridorsIndexRoute
  DashboardDashboardOperationsIndexRoute: typeof DashboardDashboardOperationsIndexRoute
  DashboardDashboardPartnersIndexRoute: typeof DashboardDashboardPartnersIndexRoute
  DashboardDashboardReportsIndexRoute: typeof DashboardDashboardReportsIndexRoute
  DashboardDashboardTransactionsIndexRoute: typeof DashboardDashboardTransactionsIndexRoute
  DashboardDashboardWalletManagementIndexRoute: typeof DashboardDashboardWalletManagementIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardComplianceIndexRoute:
    DashboardDashboardComplianceIndexRoute,
  DashboardDashboardCorridorsIndexRoute: DashboardDashboardCorridorsIndexRoute,
  DashboardDashboardOperationsIndexRoute:
    DashboardDashboardOperationsIndexRoute,
  DashboardDashboardPartnersIndexRoute: DashboardDashboardPartnersIndexRoute,
  DashboardDashboardReportsIndexRoute: DashboardDashboardReportsIndexRoute,
  DashboardDashboardTransactionsIndexRoute:
    DashboardDashboardTransactionsIndexRoute,
  DashboardDashboardWalletManagementIndexRoute:
    DashboardDashboardWalletManagementIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
